# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-13 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180512_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecords',
            name='reason_choice',
            field=models.CharField(choices=[('入库', '入库'), ('出库', '出库'), ('其他', '其他')], default='其他', max_length=100),
        ),
    ]
