# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='qqNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='weixinNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
