# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20180410_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('costprice', models.FloatField(default=0, max_length=100)),
                ('saleprice', models.FloatField(default=0, max_length=100)),
                ('initotal', models.FloatField(default=0, max_length=100)),
                ('desc', models.TextField(null=True)),
                ('create_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0)),
                ('count', models.IntegerField(default=0)),
                ('old_total', models.IntegerField(default=0)),
                ('opration_type', models.CharField(choices=[('出库', '出库'), ('入库', '入库')], default='入库', max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create time')),
                ('change_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Account')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('area', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storehouse', to='goods.StoreHouse'),
        ),
    ]
