# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodschanges',
            name='to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
