# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_auto_20180525_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('phone_number', models.CharField(max_length=100, verbose_name='电话号码')),
                ('charge_person', models.CharField(max_length=100, verbose_name='负责人')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('relative', models.CharField(max_length=100)),
                ('remark', models.TextField(max_length=1000, verbose_name='remark')),
                ('goods', models.ManyToManyField(blank=True, to='goods.Goods')),
            ],
        ),
    ]
